# Generated by Django 3.2 on 2023-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_modelfive_modelfour_modelone_modelthree_modeltwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfour',
            old_name='tags',
            new_name='xtags',
        ),
        migrations.RenameField(
            model_name='modelone',
            old_name='tags',
            new_name='xtags',
        ),
        migrations.RenameField(
            model_name='modeltwo',
            old_name='tags',
            new_name='xtags',
        ),
    ]
