name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: "3.8"
            django-version: Django==3.0
            taggit-version: django-taggit==2.1.0
            restframework-version: djangorestframework==3.13.0

          - python-version: "3.8"
            django-version: Django==3.1
            taggit-version: django-taggit==2.1.0
            restframework-version: djangorestframework==3.13.0

          - python-version: "3.8"
            django-version: Django==3.2
            taggit-version: django-taggit
            restframework-version: djangorestframework

          - python-version: "3.9"
            django-version: Django==4.0
            taggit-version: django-taggit
            restframework-version: djangorestframework

          - python-version: "3.9"
            django-version: Django==4.1
            taggit-version: django-taggit
            restframework-version: djangorestframework

          - python-version: "3.10"
            django-version: Django==4.2
            taggit-version: django-taggit
            restframework-version: djangorestframework

          - python-version: "3.11"
            django-version: Django==5.0
            taggit-version: django-taggit
            restframework-version: djangorestframework

          - python-version: "3.11"
            django-version: Django==5.1
            taggit-version: django-taggit
            restframework-version: djangorestframework

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage wheel
        pip install ${{ matrix.django-version }}
        pip install ${{ matrix.taggit-version }}
        pip install ${{ matrix.restframework-version }}
        pip install --editable ./

    - name: Run Tests
      run: coverage run --source=taggit_ui tests/manage.py test testapp

    - name: Create coverage lcov file
      run: coverage lcov -o coverage.lcov

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.python-version }}-${{ matrix.django-version }}
        path-to-lcov: coverage.lcov
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true